apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lw5trrtnc-python
  janus-idp.io/tekton: lw5trrtnc-python
  backstage.io/kubernetes-id: lw5trrtnc-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: lw5trrtnc-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
